[package]
name = "snartnet-client"
version = "0.1.1"
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
snartnet-core = { path = "../core" }
serde = { workspace = true }
serde_json = { workspace = true }
base64 = { workspace = true }
blake3 = { workspace = true }
chrono = { workspace = true }
futures = "0.3"
librqbit = { version = "9.0.1", default-features = false, features = ["rust-tls"] }
mainline = "8.0.0"
tokio = { version = "1", features = ["rt-multi-thread", "sync", "time"] }

tempfile = "3"
