/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const create_profile: (a: number, b: number, c: number, d: number) => [number, number, number];
export const update_profile: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number];
export const sign_profile: (a: number, b: number, c: number, d: number) => [number, number, number];
export const verify_profile: (a: number, b: number) => [number, number, number];
export const generate_profile_magnet_uri: (a: number, b: number) => [number, number, number, number];
export const create_direct_message: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number];
export const sign_message: (a: number, b: number, c: number, d: number) => [number, number, number];
export const verify_message: (a: number, b: number, c: number, d: number) => [number, number, number];
export const generate_keypair: () => [number, number, number];
export const sign_data: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const verify_signature_wasm: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number];
export const __wbg_snartnetcore_free: (a: number, b: number) => void;
export const snartnetcore_new: () => number;
export const snartnetcore_init: (a: number) => [number, number];
export const snartnetcore_create_profile: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
export const snartnetcore_get_current_profile: (a: number) => [number, number, number];
export const snartnetcore_update_current_profile: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const snartnetcore_create_post: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number];
export const snartnetcore_create_message: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const snartnetcore_get_public_key: (a: number) => [number, number, number, number];
export const snartnetcore_get_fingerprint: (a: number) => [number, number, number, number];
export const snartnetcore_has_profile: (a: number) => number;
export const storage_set_item: (a: number, b: number, c: number, d: number) => [number, number];
export const storage_get_item: (a: number, b: number) => [number, number, number];
export const storage_remove_item: (a: number, b: number) => [number, number];
export const create_post: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number];
export const sign_post: (a: number, b: number, c: number, d: number) => [number, number, number];
export const verify_post: (a: number, b: number, c: number, d: number) => [number, number, number];
export const init_core: () => [number, number];
export const main: () => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_4: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
