[package]
name = "snartnet-android-bridge"
version = "0.1.1"
edition = "2021"
license = "AGPL-3.0-only"

[lib]
crate-type = ["cdylib"]

[dependencies]
snartnet-client = { path = "../client" }
snartnet-core = { path = "../core" }
serde = { workspace = true }
serde_json = { workspace = true }
jni = "0.21"
base64 = { workspace = true }
qrcode = "0.14"
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
rqrr = "0.10"
