name: Compile Linux

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  compile-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Compile workspace
        run: cargo build --workspace
